---
- name: Start HANA DBs
  #command: /usr/sap/RHE/HDB00/exe/Python/bin/python /usr/sap/RHE/SYS/exe/hdb/python_support/fullSystemInfoDump.py -t RHE
  hosts: hanas
  become: true
  #become_method: su
  become_user: rheadm
  #become_flags: '-s /bin/sh'

  tasks:
   - name: Start HANA
     action: command /hana/shared/RHE/HDB00/HDB info
     register: result

   - debug: msg="{{result.stdout}}"
